/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/broadband/at_point": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Broadband At Point
         * @description Find broadband availability at a given point.
         *
         *     Uses a two-phase approach:
         *     1. Use bounding boxes to quickly filter candidate census blocks
         *     2. Perform exact spatial check on candidates
         *     3. Join with broadband data
         *
         *     This avoids loading full geometries for blocks that can't possibly contain the point.
         */
        get: operations["broadband_at_point_broadband_at_point_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transmission/at_point": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transmission At Point
         * @description Find transmission lines at a given point.
         *
         *     Queries the resilience_power.parquet file from S3 and returns transmission
         *     lines within the specified radius of the given coordinate.
         *
         *     Uses bbox pre-filtering for fast queries.
         */
        get: operations["transmission_at_point_transmission_at_point_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/s3-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug S3 */
        get: operations["debug_s3_debug_s3_access_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/geo_sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Geo Sample
         * @description Debug endpoint to check what's in the geo parquet files.
         */
        get: operations["debug_geo_sample_debug_geo_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/broadband_sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Broadband Sample
         * @description Debug endpoint to check what's in the broadband parquet files.
         */
        get: operations["debug_broadband_sample_debug_broadband_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/bbox_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Bbox Check
         * @description Debug endpoint to check bbox filtering.
         */
        get: operations["debug_bbox_check_debug_bbox_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Geocode Endpoint
         * @description Geocoding endpoint using OpenStreetMap Nominatim.
         *     Returns a structured GeocodingResult model.
         */
        post: operations["geocode_endpoint_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/electricity-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Electricity Price Endpoint
         * @description Get electricity price data from EIA API.
         */
        post: operations["electricity_price_endpoint_api_electricity_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/utility-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Utility Rates Endpoint
         * @description Get utility rates from OpenEI API.
         */
        post: operations["utility_rates_endpoint_api_utility_rates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transmission-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transmission Lines Endpoint
         * @description Get transmission lines data.
         */
        post: operations["transmission_lines_endpoint_api_transmission_lines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datacenter-climate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Datacenter Climate Endpoint
         * @description Get comprehensive weather data from multiple NOAA APIs.
         */
        post: operations["datacenter_climate_endpoint_api_datacenter_climate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/water-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Water Resources Endpoint
         * @description Get water resources data from USGS APIs.
         */
        post: operations["water_resources_endpoint_api_water_resources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wind-turbines-by-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wind Turbines By State Endpoint
         * @description Get wind turbines by state from USGS API.
         */
        post: operations["wind_turbines_by_state_endpoint_api_wind_turbines_by_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wind-turbines-near-location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wind Turbines Near Location Endpoint
         * @description Get wind turbines near location from USGS API.
         */
        post: operations["wind_turbines_near_location_endpoint_api_wind_turbines_near_location_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/broadband-connectivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Broadband Connectivity Endpoint
         * @description Get broadband connectivity data.
         */
        post: operations["broadband_connectivity_endpoint_api_broadband_connectivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transportation-logistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transportation Logistics Endpoint
         * @description Get comprehensive transportation data.
         */
        post: operations["transportation_logistics_endpoint_api_transportation_logistics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/highway-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Highway Access Endpoint
         * @description Get highway access data.
         */
        post: operations["highway_access_endpoint_api_highway_access_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rail-connectivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rail Connectivity Endpoint
         * @description Get rail connectivity data.
         */
        post: operations["rail_connectivity_endpoint_api_rail_connectivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BroadbandProvider
         * @description Broadband provider information.
         */
        BroadbandProvider: {
            /** Provider Id */
            provider_id?: string | null;
            /** Provider Name */
            provider_name: string;
            /** Technology */
            technology: string;
            /** Max Download Speed Mbps */
            max_download_speed_mbps: number;
            /** Max Upload Speed Mbps */
            max_upload_speed_mbps: number;
            /** Low Latency */
            low_latency?: boolean | null;
            /** Business Service */
            business_service?: boolean | null;
            /** Consumer Service */
            consumer_service?: boolean | null;
        };
        /**
         * BroadbandResponse
         * @description Broadband connectivity API response.
         */
        BroadbandResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default Broadband_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /** Radius Km */
            radius_km: number;
            /**
             * Census Blocks
             * @default []
             */
            census_blocks: components["schemas"]["CensusBlock"][];
            /**
             * Unique Providers
             * @default []
             */
            unique_providers: string[];
            /**
             * Fiber Providers
             * @default []
             */
            fiber_providers: string[];
            /**
             * Max Speeds
             * @default {}
             */
            max_speeds: {
                [key: string]: number;
            };
            /**
             * Blocks Searched
             * @default 0
             */
            blocks_searched: number;
            /**
             * Blocks With Service
             * @default 0
             */
            blocks_with_service: number;
        };
        /**
         * CensusBlock
         * @description Census block with broadband data.
         */
        CensusBlock: {
            /** Block Geoid */
            block_geoid: string;
            /** Distance Km */
            distance_km: number;
            /**
             * Providers
             * @default []
             */
            providers: components["schemas"]["BroadbandProvider"][];
            /** Max Download Available */
            max_download_available?: number | null;
            /** Max Upload Available */
            max_upload_available?: number | null;
            /**
             * Fiber Available
             * @default false
             */
            fiber_available: boolean;
            /**
             * Business Fiber Available
             * @default false
             */
            business_fiber_available: boolean;
        };
        /** CityRequest */
        CityRequest: {
            /** City */
            city: string;
        };
        /**
         * ClimateDataResponse
         * @description Climate data API response.
         */
        ClimateDataResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default NOAA_APIs
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /** Current Conditions */
            current_conditions?: {
                [key: string]: unknown;
            } | null;
            /**
             * Active Alerts
             * @default []
             */
            active_alerts: components["schemas"]["WeatherAlert"][];
            nearest_station?: components["schemas"]["WeatherStation"] | null;
            /**
             * Historical Summary
             * @default {}
             */
            historical_summary: {
                [key: string]: unknown;
            };
            /**
             * Historical Data
             * @default []
             */
            historical_data: components["schemas"]["HistoricalWeatherData"][];
            /**
             * Years Of Data
             * @default 5
             */
            years_of_data: number;
        };
        /**
         * Coordinates
         * @description Geographic coordinates.
         */
        Coordinates: {
            /**
             * Lat
             * @description Latitude
             */
            lat: number;
            /**
             * Lon
             * @description Longitude
             */
            lon: number;
        };
        /** CoordinatesRequest */
        CoordinatesRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /**
         * ElectricityPriceData
         * @description EIA electricity price data point.
         */
        ElectricityPriceData: {
            /** Period */
            period: string;
            /** State Id */
            state_id: string;
            /** State Name */
            state_name: string;
            /** Sector */
            sector: string;
            /**
             * Price
             * @description Price in cents per kWh
             */
            price: number;
            /**
             * Sales
             * @description Sales in million kWh
             */
            sales?: number | null;
            /**
             * Revenue
             * @description Revenue in million dollars
             */
            revenue?: number | null;
        };
        /**
         * ElectricityPriceResponse
         * @description Electricity price API response.
         */
        ElectricityPriceResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default EIA_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            /** City */
            city: string;
            /** State */
            state: string;
            latest_price?: components["schemas"]["ElectricityPriceData"] | null;
            /**
             * Historical Data
             * @default []
             */
            historical_data: components["schemas"]["ElectricityPriceData"][];
            /**
             * Units
             * @default cents/kWh
             */
            units: string;
        };
        /** GeocodeRequest */
        GeocodeRequest: {
            /** City */
            city: string;
        };
        /**
         * GeocodingResult
         * @description Geocoding API response.
         */
        GeocodingResult: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default OpenStreetMap Nominatim
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            /** City */
            city: string;
            /** Display Name */
            display_name?: string | null;
            coordinates: components["schemas"]["Coordinates"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HighwayAccessResponse
         * @description Highway access API response.
         */
        HighwayAccessResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default Overpass_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /**
             * Search Radius Km
             * @default 50
             */
            search_radius_km: number;
            /**
             * Motorways
             * @default []
             */
            motorways: components["schemas"]["TransportationFeature"][];
            /**
             * Trunk Roads
             * @default []
             */
            trunk_roads: components["schemas"]["TransportationFeature"][];
            /**
             * Junctions
             * @default []
             */
            junctions: components["schemas"]["TransportationFeature"][];
            /** Nearest Highway Km */
            nearest_highway_km?: number | null;
            /** Nearest Junction Km */
            nearest_junction_km?: number | null;
            /**
             * Total Features
             * @default 0
             */
            total_features: number;
        };
        /**
         * HistoricalWeatherData
         * @description Historical weather data point.
         */
        HistoricalWeatherData: {
            /** Date */
            date: string;
            /**
             * Temp Max
             * @description Maximum temperature in °F
             */
            temp_max?: number | null;
            /**
             * Temp Min
             * @description Minimum temperature in °F
             */
            temp_min?: number | null;
            /**
             * Precipitation
             * @description Precipitation in inches
             */
            precipitation?: number | null;
            /**
             * Snow
             * @description Snowfall in inches
             */
            snow?: number | null;
            /**
             * Wind Speed
             * @description Average wind speed in mph
             */
            wind_speed?: number | null;
        };
        /**
         * RailConnectivityResponse
         * @description Rail connectivity API response.
         */
        RailConnectivityResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default Overpass_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /**
             * Search Radius Km
             * @default 100
             */
            search_radius_km: number;
            /**
             * Rail Lines
             * @default []
             */
            rail_lines: components["schemas"]["TransportationFeature"][];
            /**
             * Stations
             * @default []
             */
            stations: components["schemas"]["TransportationFeature"][];
            /** Nearest Rail Km */
            nearest_rail_km?: number | null;
            /** Nearest Station Km */
            nearest_station_km?: number | null;
            /** Freight Capable */
            freight_capable?: boolean | null;
            /**
             * Total Features
             * @default 0
             */
            total_features: number;
        };
        /**
         * TransmissionLine
         * @description Transmission line feature.
         */
        TransmissionLine: {
            /** Line Id */
            line_id?: string | null;
            /** Voltage Kv */
            voltage_kv?: number | null;
            /** Owner */
            owner?: string | null;
            /** Status */
            status?: string | null;
            /** Distance Km */
            distance_km: number;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
        };
        /**
         * TransmissionLinesResponse
         * @description Transmission lines API response.
         */
        TransmissionLinesResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default Transmission_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /** Radius Km */
            radius_km: number;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["TransmissionLine"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * TransportationFeature
         * @description Transportation infrastructure feature.
         */
        TransportationFeature: {
            /** Osm Id */
            osm_id?: string | null;
            feature_type: components["schemas"]["TransportationType"];
            /** Name */
            name?: string | null;
            /**
             * Ref
             * @description Reference number (e.g., I-80)
             */
            ref?: string | null;
            /**
             * Classification
             * @description e.g., motorway, trunk, primary
             */
            classification?: string | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /**
             * Tags
             * @default {}
             */
            tags: {
                [key: string]: unknown;
            };
        };
        /**
         * TransportationResponse
         * @description Transportation logistics API response.
         */
        TransportationResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default Overpass_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /** Search Radius Km */
            search_radius_km: number;
            /**
             * Highways
             * @default []
             */
            highways: components["schemas"]["TransportationFeature"][];
            /**
             * Railways
             * @default []
             */
            railways: components["schemas"]["TransportationFeature"][];
            /**
             * Airports
             * @default []
             */
            airports: components["schemas"]["TransportationFeature"][];
            /**
             * Ports
             * @default []
             */
            ports: components["schemas"]["TransportationFeature"][];
            /**
             * Highway Junctions
             * @default []
             */
            highway_junctions: components["schemas"]["TransportationFeature"][];
            /**
             * Rail Stations
             * @default []
             */
            rail_stations: components["schemas"]["TransportationFeature"][];
            /**
             * Total Features
             * @default 0
             */
            total_features: number;
        };
        /**
         * TransportationType
         * @description Types of transportation infrastructure.
         * @enum {string}
         */
        TransportationType: "highway" | "railway" | "airport" | "port" | "junction";
        /**
         * UtilityRate
         * @description Individual utility rate structure.
         */
        UtilityRate: {
            /** Utility Name */
            utility_name: string;
            /** Rate Name */
            rate_name: string;
            /** Sector */
            sector: string;
            /** Description */
            description?: string | null;
            /**
             * Fixed Charge
             * @description Fixed monthly charge in dollars
             */
            fixed_charge?: number | null;
            /**
             * Demand Charge
             * @description Demand charge in $/kW
             */
            demand_charge?: number | null;
            /**
             * Energy Charge
             * @description Energy charge in $/kWh
             */
            energy_charge?: number | null;
            /** Minimum Charge */
            minimum_charge?: number | null;
            /** Effective Date */
            effective_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Approved
             * @default true
             */
            approved: boolean;
            /** Uri */
            uri?: string | null;
        };
        /**
         * UtilityRatesResponse
         * @description Utility rates API response.
         */
        UtilityRatesResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default OpenEI_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /**
             * Rates
             * @default []
             */
            rates: components["schemas"]["UtilityRate"][];
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Radius Searched
             * @description Search radius in miles
             * @default 10
             */
            radius_searched: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WaterMonitoringSite
         * @description Water monitoring site.
         */
        WaterMonitoringSite: {
            /** Site Id */
            site_id: string;
            /** Site Name */
            site_name: string;
            site_type: components["schemas"]["WaterSiteType"];
            coordinates: components["schemas"]["Coordinates"];
            /** Distance Km */
            distance_km?: number | null;
            /**
             * Agency
             * @default USGS
             */
            agency: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Parameters Monitored
             * @default []
             */
            parameters_monitored: string[];
            /** Drainage Area Sq Mi */
            drainage_area_sq_mi?: number | null;
            /** Well Depth Ft */
            well_depth_ft?: number | null;
        };
        /**
         * WaterResourcesResponse
         * @description Water resources API response.
         */
        WaterResourcesResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default USGS_APIs
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            coordinates: components["schemas"]["Coordinates"];
            /**
             * Radius Miles
             * @default 25
             */
            radius_miles: number;
            /**
             * Surface Water Sites
             * @default []
             */
            surface_water_sites: components["schemas"]["WaterMonitoringSite"][];
            /**
             * Groundwater Sites
             * @default []
             */
            groundwater_sites: components["schemas"]["WaterMonitoringSite"][];
            /**
             * Total Sites
             * @default 0
             */
            total_sites: number;
        };
        /**
         * WaterSiteType
         * @description Types of water monitoring sites.
         * @enum {string}
         */
        WaterSiteType: "surface_water" | "groundwater" | "spring" | "reservoir";
        /**
         * WeatherAlert
         * @description Active weather alert.
         */
        WeatherAlert: {
            /** Id */
            id: string;
            /** Event */
            event: string;
            /** Severity */
            severity: string;
            /** Urgency */
            urgency: string;
            /** Certainty */
            certainty: string;
            /** Headline */
            headline: string;
            /** Description */
            description?: string | null;
            /** Onset */
            onset?: string | null;
            /** Expires */
            expires?: string | null;
        };
        /**
         * WeatherStation
         * @description Weather station information.
         */
        WeatherStation: {
            /** Station Id */
            station_id: string;
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Elevation */
            elevation?: number | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Data Coverage */
            data_coverage?: number | null;
        };
        /**
         * WindTurbine
         * @description Wind turbine information.
         */
        WindTurbine: {
            /** Project Name */
            project_name?: string | null;
            /** Project Year */
            project_year?: number | null;
            /** Turbine Capacity Kw */
            turbine_capacity_kw?: number | null;
            /** Hub Height M */
            hub_height_m?: number | null;
            /** Rotor Diameter M */
            rotor_diameter_m?: number | null;
            /** Total Height M */
            total_height_m?: number | null;
            coordinates: components["schemas"]["Coordinates"];
            /**
             * Offshore
             * @default false
             */
            offshore: boolean;
            /** Confidence Level */
            confidence_level?: number | null;
            /** Distance Km */
            distance_km?: number | null;
        };
        /**
         * WindTurbinesResponse
         * @description Wind turbines API response.
         */
        WindTurbinesResponse: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Source
             * @default USGS_Wind_API
             */
            source: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Error */
            error?: string | null;
            /** Location */
            location: string | components["schemas"]["Coordinates"];
            /**
             * Turbines
             * @default []
             */
            turbines: components["schemas"]["WindTurbine"][];
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Total Capacity Mw
             * @default 0
             */
            total_capacity_mw: number;
            /** Search Radius Km */
            search_radius_km?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    broadband_at_point_broadband_at_point_get: {
        parameters: {
            query: {
                /** @description Longitude (WGS84) */
                lon: number;
                /** @description Latitude (WGS84) */
                lat: number;
                /** @description Search radius in kilometers */
                radius_km?: number;
                /** @description Minimum download speed in Mbps */
                min_download?: number | null;
                /** @description Minimum upload speed in Mbps */
                min_upload?: number | null;
                /** @description Max results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transmission_at_point_transmission_at_point_get: {
        parameters: {
            query: {
                /** @description Longitude (WGS84) */
                lon: number;
                /** @description Latitude (WGS84) */
                lat: number;
                /** @description Search radius in kilometers */
                radius_km?: number;
                /** @description Max results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_s3_debug_s3_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    debug_geo_sample_debug_geo_sample_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_broadband_sample_debug_broadband_sample_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_bbox_check_debug_bbox_check_get: {
        parameters: {
            query: {
                /** @description Longitude */
                lon: number;
                /** @description Latitude */
                lat: number;
                /** @description Radius in km */
                radius_km?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_endpoint_geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    electricity_price_endpoint_api_electricity_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectricityPriceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    utility_rates_endpoint_api_utility_rates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilityRatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transmission_lines_endpoint_api_transmission_lines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransmissionLinesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datacenter_climate_endpoint_api_datacenter_climate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClimateDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    water_resources_endpoint_api_water_resources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterResourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wind_turbines_by_state_endpoint_api_wind_turbines_by_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindTurbinesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wind_turbines_near_location_endpoint_api_wind_turbines_near_location_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindTurbinesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    broadband_connectivity_endpoint_api_broadband_connectivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadbandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transportation_logistics_endpoint_api_transportation_logistics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    highway_access_endpoint_api_highway_access_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighwayAccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rail_connectivity_endpoint_api_rail_connectivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoordinatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RailConnectivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
